/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutorRouteImport } from './routes/autor'
import { Route as LivroRouteImport } from './routes/livro'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as CapitulosSlugRouteImport } from './routes/capitulos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorRoute = AutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroRoute = LivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitulosSlugRoute = CapitulosSlugRouteImport.update({
  id: '/capitulos/$slug',
  path: '/capitulos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/livro': typeof LivroRoute
  '/sobre': typeof SobreRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/livro': typeof LivroRoute
  '/sobre': typeof SobreRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autor': typeof AutorRoute
  '/livro': typeof LivroRoute
  '/sobre': typeof SobreRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autor' | '/livro' | '/sobre' | '/capitulos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autor' | '/livro' | '/sobre' | '/capitulos/$slug'
  id: '__root__' | '/' | '/autor' | '/livro' | '/sobre' | '/capitulos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorRoute: typeof AutorRoute
  LivroRoute: typeof LivroRoute
  SobreRoute: typeof SobreRoute
  CapitulosSlugRoute: typeof CapitulosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor': {
      id: '/autor'
      path: '/autor'
      fullPath: '/autor'
      preLoaderRoute: typeof AutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro': {
      id: '/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof LivroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulos/$slug': {
      id: '/capitulos/$slug'
      path: '/capitulos/$slug'
      fullPath: '/capitulos/$slug'
      preLoaderRoute: typeof CapitulosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorRoute: AutorRoute,
  LivroRoute: LivroRoute,
  SobreRoute: SobreRoute,
  CapitulosSlugRoute: CapitulosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
